### ISSUE TITLE
Unable to cache Oculus

### ISSUE THREAD

**Issue by mscrnt** [zeropingheroes/lancache#3]
Not sure if Oculus uses HTTPS or not, but it's not working for me. 

Have you looked into doing this already?

**Comment by ilumos** [comment]
Hi there,

Only upstreams configured in [lancache/upstreams](https://github.com/zeropingheroes/lancache/tree/master/upstreams) and with matching DNS overrides in [zeropingheroes/lancache-dns](https://github.com/zeropingheroes/lancache-dns) will be cached.

Feel free to experiment with caching Oculus content by copying one of the existing upstreams! :)

**Comment by mscrnt** [comment]
Hi,

Thanks for the response. I've tried what you suggested. However, I might have missed something somewhere. The url that the Oculus client pulls from seems to be redirected to the lancache when I ping it, but I don't see any network traffic on the network device nor do I see it caching anything.  I think I might be missing some of their CDN's. I am not sure. 

Anyways, let me know if you ever decide to look into adding this feature.

Thanks

**Comment by ilumos** [comment]
Sure thing, if / when Occulus become mass market I'll see if its possible to cache their content. For now I'll close this off :)
