### ISSUE TITLE
fix for the corrupt steam downloads

### ISSUE THREAD

**Issue by wagex** [zeropingheroes/lancache#4]
i had this exact issue for a long time trying to get it to run under ubuntu in a hyper-v no matter what i tried it always ended up with a corrupt download. made the switch over to centos 7 and that solved my issue, i think it had something to do with the network stacks centos 7 is based on RHEL so i guess it just works better with hyper-v.  the reason i say that is because the same EXACT setup on a physical machine by itself ran the lancache fine. hope this helps, sorry wasnt sure where to put a comment at.

edit: heres a link to a thread i was working on trying to solve the downloads pausing because steam detected corrupt files http://www.overclockers.com/forums/showthread.php/773323-how-to-configure-lancache-in-ubuntu-16-04-under-hyper-V
only two fixes worked one was changing it to a legacy nic in hyper-v problem with that is 100mbs is slow fix two was to switch to centos 7 and that made everything run fine.

**Comment by ilumos** [comment]
Hi wagex, thanks for sharing. I'll close this off so that others can find and benefit from it.

**Comment by wagex** [comment]
no problem, hope it helps with your steam issues!
