### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by ScholliYT** [zeropingheroes/lancache#5]
So you say I need to have nginx installed with slice 
`Nginx compiled with slice and pcre modules`.
I did that and have nginx up and running now. 

But when I now try to: 

> git clone https://github.com/zeropingheroes/lancache.git /etc/nginx

I get: fatal: **destination path '/etc/nginx' already exists and is not an empty directory.**

Seems to be resonable for me since nginx is installed. What exactly do you mean by having nginx compiled with slice?

**Comment by ilumos** [comment]
Hi there,

Yes that's a reasonable error to get! Try cloning to another directory first, and then moving everything into the `/etc/nginx/` directory

Something like:

    $ git clone https://github.com/zeropingheroes/lancache.git ~/lancache
    $ sudo mv ~/lancache/* /etc/nginx/ 

As a side note, you can also use [zeropingheroes/lancache-installer](https://github.com/zeropingheroes/lancache-installer) to do all this for you.

Thanks for identifying this problem - I'll update the docs :)

**Comment by ScholliYT** [comment]
`$ sudo mv ~/lancache/* /etc/nginx/ ` gives me the same error. I just uses the linked installer script and it worked fine 🥇
